### ISSUE TITLE
Sentry Buster spawning on Engineer carrying built exit

### ISSUE THREAD

**Issue by Darkita162** [Mikusch/MannVsMann#18]
So, today I was being lazy and decided to just experiment with how sneaky I can make the Sentry Buster, example being having it spawn behind enemy lines and such. But during that experiementing I noticed that if you carry a teleporter exit thats already been built, the Sentry Buster will spawn on top of the Engineer. I suspect this is because its locating the teleporter on the Engineer, to which I dont know if this is intentional or not. However I dont see any real way to abuse this either as you'll be making yourself more of a target by being marked for death. Just thought I'd point that out.

_(I actually just thought of a way to abuse it. The Engineer can stand in areas where he cant normally build, having the Sentry Buster spawn in places it shouldn't and possibly get stuck)_

To replicate this, simply build a teleporter exit at any level and haul it. If the enemy team has an active sentry that meets the requirements to spawn a Sentry Buster, it will spawn on top of you.

**Comment by Mikusch** [comment]
wrong repo
