### ISSUE TITLE
Refund upgrade doesn't track capture bonus money

### ISSUE THREAD

**Issue by HellsReindeer** [Mikusch/MannVsMann#24]
Refunding when you have bonus money from captures doesn't properly refund.
Example: Start with 400, capture point and receive 100 to total 500 credits. Refunding will give 400 instead of the expected 500.

**Comment by Mikusch** [comment]
This is a very old bug I can't really make much sense of. On successful point capture the currency gets distributed by the game (not us) by calling `DistributeCurrencyAmount`, which in turn should call our detour, but doesn't. Hence the plugin never knows of this extra currency.

This does not happen with CTF flag captures, so I'm not really sure where to begin with this.

**Comment by Mikusch** [comment]
Just to follow up on this; I found out that this is an issue specifically on Windows servers. All bonus currency is tracked correctly on Linux. There is nothing I can really do to fix this, as it's caused by compiler shenanigans.
