### ISSUE TITLE
AI compatibility

### ISSUE THREAD

**Issue by plasmawario** [Mikusch/MannVsMann#33]
I've noticed that on some maps, mainly ones from cp, koth, plr, and some others, bot players seem to have their AI disabled or their AI just doesn't work. They just sit at spawn.

Most of the maps from pl and ctf seem to have bots work just fine.

I'm wondering if there is a list of maps that bot AI will work properly on or if i will have to experiment myself. Thanks!

**Comment by Mikusch** [comment]
Hello, are you sure this is an issue with the plugin? Some game types do not natively support bots (like Payload Race). For others, it's possible that the map you're using does not have a nav mesh. Try running `nav_generate` and see if that fixes your problem.

**Comment by plasmawario** [comment]
You know what i completely forgot about maps having nav meshes. Yeah, having nav meshes does indeed fix the problem. My apologies!
