### ISSUE TITLE
Question regarding the explosive headshot

### ISSUE THREAD

**Issue by higps** [Mikusch/MannVsMann#5]
I'm making a gamemode with giant robots, and we are going to make it compatible with this mode.

One question though, how do you get the explosive headshots to work? In regular TF2 adding the attribute does nothing.

I've looked over the code, but I can't find anything that specifically ties it to that attribute.

Does it have something to do with setting the mode to be mvm?

**Comment by Mikusch** [comment]
There is a check for `CTFGameRules::GameModeUsesUpgrades` in `CTFPlayer::OnTakeDamage_Alive`. There's a detour that handles it.

https://github.com/Mikusch/MannVsMann/blob/ee1d1aa8343d7f922c2686b64d5e8ed25e66807e/addons/sourcemod/scripting/mannvsmann/dhooks.sp#L172-L177
