### ISSUE TITLE
Canteen upgrade refund bug  

### ISSUE THREAD

**Issue by gaejuck** [Mikusch/MannVsMann#6]
1. Buy 3 canteen.
2. Upgrade anything.
3. Refund upgrade without pressing Apply button.
4. All upgrade costs will be refunded. but upgrade will be maintained.

Reproducing the situation
https://youtu.be/Q-zomOUtrLk

**Comment by Mikusch** [comment]
I can't reproduce this. There is a different bug where the money spent on upgrades gets refunded back, but not what the video shows.

**Comment by gaejuck** [comment]
What are some situations where MvMPlayer(param1).RemoveAllUpgrades() doesn't work properly?
What influences this function? Do you have any idea with this?

**Comment by Mikusch** [comment]
I think I've figured it out. Will need to look into it further. From what I can see, `CPopulationManager::RemovePlayerAndItemUpgradesFromHistory` will refund some currency despite the plugin already doing it. If this is the cause, I will try to get a fix out shortly.
